### ISSUE TITLE
Multiplayer only gives accessory moonstones

### ISSUE THREAD

**Issue by Yangfu1000** [Beetrootmonkey/Moonstones#2]
Hi Beetrootmonkey,

I was doing a modded multiplayer playthrough with some friends. I noticed that every single time anyone clicked the dormant moonstone, it would always give an accessory. So, a full stack of dormant moonstones later, there was not a singular weapon moonstone...

I'm also a coder, so I downloaded the mod files and did some debugging. I don't know if this is a mistake in the API or the mod but I found a solution to fix the bug.

In line 31 of MoonstoneBlank.cs I changed it to

if (Main.rand.Next(2) == 1)

instead of

if (Main.rand.Next(1) != 0)

That was the only change I found was needed.
I tested the edited code with another full stack of dormant moonstones just to see if it was a 50 50 chance to get a weapon or accessory. It seemed to be successful having about a 50 50 chance give or take a few.

I have not used this in Singleplayer, but I just wanted to let you know and give a suggestion how to fix it.

In the event that you accept my suggestion, I hope that it helps and possibly give me recognition?

Sincerely,

Yangfu1000- The Shy Coder

**Comment by Beetrootmonkey** [comment]
Thanks for the feedback! I'm like 90% sure that I changed that specific line to always yield '1' so I could test something with accessory moonstones; but appareantly I forgot to change it back lol. Now that you mention it, I also remember only getting accessory stones in our multiplayer playthrough.

**Comment by Beetrootmonkey** [comment]
I now remembered why I put in mentioned line. I hadn't (and still haven't) figured out a way to make sure items can receive the chosen modifier (so far ranged/magic weapons can receive modifiers like 'legendary', even though vanilla mechanics don't allow that).

**Comment by Beetrootmonkey** [comment]
Fixed as of 1.0.6.
